### ISSUE TITLE
Workflows appear to never get approved

### ISSUE THREAD

**Issue by TiviPlus** [mheap/automatic-approve-action#5]
It looks like workflows will get noticed, but will always say that "No runs found for the following workflows:"

Examples:
Unapproved workflow run for new contributor:
https://github.com/tgstation/TerraGov-Marine-Corps/actions/runs/854665717

Action seeing the unapproved workflow, but saying that it's not the correct one despite being correct:
https://github.com/tgstation/TerraGov-Marine-Corps/runs/2614414414?check_suite_focus=true 

Example from other repo indicating similar issue:
https://github.com/OctoPrint/plugins.octoprint.org/runs/2615953510?check_suite_focus=true

**Comment by mheap** [comment]
Thanks for raising this issue. My test workflows didn't contain a `name` property which meant that they defaulted to the path (which the action depended on).

I've just released v1.0.4 which solves the issue when using named workflows. `v1` will be retagged so keep an eye on your scheduled action and it _should_ start approving outstanding runs automatically.

**Comment by mheap** [comment]
Just checked and the linked workflow run is now executing

![image](https://user-images.githubusercontent.com/59130/118822359-00140900-b8b0-11eb-8fbe-8d34fc4a9754.png)

**Comment by TiviPlus** [comment]
Thank you!
