### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError

### ISSUE THREAD

**Issue by palfrey** [mheap/automatic-approve-action#9]
Demo of issue: https://github.com/rust-unofficial/awesome-rust/runs/2817827504?check_suite_focus=true

```
Run mheap/automatic-approve-action@v1.0.5
(node:1413) UnhandledPromiseRejectionWarning: HttpError
    at /home/runner/work/_actions/mheap/automatic-approve-action/v1.0.5/dist/index.js:3652:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async action (/home/runner/work/_actions/mheap/automatic-approve-action/v1.0.5/dist/index.js:30:24)
(node:1413) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1413) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Not quite sure where to start with debugging this one?

**Comment by mheap** [comment]
There seems to be an issue with the GitHub API. I've raised it with the team

```
curl -I "https://api.github.com/repos/rust-unofficial/awesome-rust/actions/runs?status=action_required"
```

Thanks for the heads up!

**Comment by palfrey** [comment]
Possibly also worth making the script exit with non-zero in this sort of case? I was only seeing this because I dug into the logs, but that action run is marked as succeeding currently.

**Comment by mheap** [comment]
I've just released v1.1.0 that improves the error handling to make this more obvious. If you're pointing at `@v1` your workflow will automatically be updated to use the new version.

Unfortuanately there's an issue with the metadata for the `awesome-rust` repository on the GitHub side so there's nothing I can do to fix this specific issue. @cschleiden is looking into it

**Comment by palfrey** [comment]
Thanks. I've upgraded and it's at least now failing in a readable way! https://github.com/rust-unofficial/awesome-rust/runs/2829995581?check_suite_focus=true

**Comment by foosel** [comment]
Ah, good to know it's not just me. I'm seeing the 500s as well on [OctoPrint/plugins.octoprint.org](https://github.com/OctoPrint/plugins.octoprint.org). @cschleiden maybe you want to check that out too, might give you additional data points

**Comment by cschleiden** [comment]
@foosel @palfrey could you try again? https://api.github.com/repos/rust-unofficial/awesome-rust/actions/runs?status=action_required, for example, should return the correct result now.

**Comment by palfrey** [comment]
@cschleiden LGTM https://github.com/rust-unofficial/awesome-rust/runs/2877408372?check_suite_focus=true

**Comment by foosel** [comment]
@cschleiden sorry, only got around to test now, all looking good again, thanks!
